server:
  port: 6002

#eureka服务器
eureka:
  instance:
    #eureka服务端的实例名称
    hostname: eureka${server.port}
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #集群指向其它eureka
      defaultZone: http://eureka6001.com:6001/eureka/
      #单机就是自己
      #defaultZone: http://eureka${server.port}.com:${server.port}/eureka/